import { DatabaseSync } from "node:sqlite";
import { createHash, randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import type { AgentResult, IntakeState, RunState, RunView, TaskRequest } from "./types.js";
import { PikoError } from "./types.js";
import { sameTask } from "./task-equality.js";
import { emptyUsage, validateUsage } from "./semantic.js";

const now=()=>new Date().toISOString();
export class TaskStore {
  readonly db:DatabaseSync;
  constructor(path:string,busyMs:number){if(path!==":memory:")mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);this.db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=${busyMs}`);this.migrate()}
  close(){this.db.close()}
  private migrate(){this.db.exec(`
CREATE TABLE IF NOT EXISTS instance_meta(key TEXT PRIMARY KEY,value_json TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS tasks(task_id TEXT PRIMARY KEY,run_id TEXT NOT NULL UNIQUE,owner_principal TEXT NOT NULL,identity_state TEXT NOT NULL CHECK(identity_state IN ('Active','Tombstone')),task_json TEXT,accepted_at TEXT NOT NULL,purge_after TEXT NOT NULL,CHECK((identity_state='Active' AND task_json IS NOT NULL) OR(identity_state='Tombstone' AND task_json IS NULL))) STRICT;
CREATE TABLE IF NOT EXISTS runs(run_id TEXT PRIMARY KEY REFERENCES tasks(run_id),state TEXT NOT NULL CHECK(state IN ('Queued','Running','Cancelling','Completed','Failed','Cancelled')),generation INTEGER NOT NULL CHECK(generation>=1),cancel_requested INTEGER NOT NULL DEFAULT 0 CHECK(cancel_requested IN(0,1)),discussion_intake_state TEXT NOT NULL CHECK(discussion_intake_state IN('Disabled','Open','Closing','Closed')),accepted_at TEXT NOT NULL,started_at TEXT,finished_at TEXT,deadline_at TEXT NOT NULL,max_model_calls INTEGER NOT NULL,max_tool_calls INTEGER NOT NULL,model_calls INTEGER NOT NULL DEFAULT 0,tool_calls INTEGER NOT NULL DEFAULT 0,last_activity_at TEXT) STRICT;
CREATE TABLE IF NOT EXISTS run_sessions(run_id TEXT PRIMARY KEY REFERENCES runs(run_id),pi_session_id TEXT NOT NULL UNIQUE,lane_name TEXT NOT NULL CHECK(lane_name='main'),active_operation_id TEXT,last_operation_id TEXT,observed_tip_id TEXT,lease_epoch INTEGER NOT NULL CHECK(lease_epoch>=1)) STRICT;
CREATE TABLE IF NOT EXISTS execution_slot(slot_id INTEGER PRIMARY KEY CHECK(slot_id=1),run_id TEXT REFERENCES runs(run_id),owner_id TEXT,boot_id TEXT,lease_epoch INTEGER NOT NULL,heartbeat_at TEXT) STRICT;
INSERT OR IGNORE INTO execution_slot(slot_id,lease_epoch) VALUES(1,0);
CREATE TABLE IF NOT EXISTS results(run_id TEXT PRIMARY KEY REFERENCES runs(run_id),generation INTEGER NOT NULL,result_json TEXT NOT NULL,result_sha256 TEXT NOT NULL,published_at TEXT NOT NULL,UNIQUE(run_id,generation)) STRICT;
CREATE TABLE IF NOT EXISTS model_attempts(run_id TEXT NOT NULL REFERENCES runs(run_id),operation_id TEXT NOT NULL,step_id TEXT NOT NULL,attempt INTEGER NOT NULL,state TEXT NOT NULL CHECK(state IN('Reserved','Started','UsageObserved','Terminal','Unknown')),raw_usage_json TEXT,record_version INTEGER NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(run_id,operation_id,step_id,attempt)) STRICT;
CREATE TABLE IF NOT EXISTS tool_calls(run_id TEXT NOT NULL REFERENCES runs(run_id),operation_id TEXT NOT NULL,tool_call_id TEXT NOT NULL,tool_name TEXT NOT NULL,effect TEXT NOT NULL,replay TEXT NOT NULL CHECK(replay IN('never','safe')),recovery_contract_ref TEXT,state TEXT NOT NULL CHECK(state IN('Reserved','Started','Terminal','Unknown')),recovery_count INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(run_id,operation_id,tool_call_id)) STRICT;
CREATE TABLE IF NOT EXISTS matrix_state(singleton INTEGER PRIMARY KEY CHECK(singleton=1),sync_cursor TEXT,membership_version INTEGER NOT NULL) STRICT; INSERT OR IGNORE INTO matrix_state VALUES(1,NULL,0);
CREATE TABLE IF NOT EXISTS matrix_events(room_id TEXT NOT NULL,event_id TEXT NOT NULL,sender TEXT NOT NULL,txn_id TEXT,observed_at TEXT NOT NULL,PRIMARY KEY(room_id,event_id)) STRICT;
CREATE TABLE IF NOT EXISTS discussion_turns(run_id TEXT NOT NULL REFERENCES runs(run_id),event_id TEXT NOT NULL,turn_seq INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN('Pending','QueuedInPi','Consumed','Abandoned')),visible_content TEXT NOT NULL,pi_entry_id TEXT,pi_operation_id TEXT,PRIMARY KEY(run_id,event_id),UNIQUE(run_id,turn_seq)) STRICT;
CREATE TABLE IF NOT EXISTS matrix_sends(txn_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(run_id),turn_seq INTEGER,payload_sha256 TEXT NOT NULL,event_id TEXT,state TEXT NOT NULL CHECK(state IN('Pending','Sent','Unknown'))) STRICT;
CREATE TABLE IF NOT EXISTS audit_events(audit_id INTEGER PRIMARY KEY AUTOINCREMENT,event_name TEXT NOT NULL,actor_class TEXT NOT NULL,run_id TEXT,detail_json TEXT NOT NULL,occurred_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS discussion_access_loss(run_id TEXT PRIMARY KEY REFERENCES runs(run_id),room_id TEXT NOT NULL,detected_at TEXT NOT NULL) STRICT;
`);const ddl=(this.db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='discussion_turns'").get() as any).sql as string;if(!ddl.includes("Abandoned")){this.db.exec(`PRAGMA foreign_keys=OFF;BEGIN IMMEDIATE;ALTER TABLE discussion_turns RENAME TO discussion_turns_v1;CREATE TABLE discussion_turns(run_id TEXT NOT NULL REFERENCES runs(run_id),event_id TEXT NOT NULL,turn_seq INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN('Pending','QueuedInPi','Consumed','Abandoned')),visible_content TEXT NOT NULL,pi_entry_id TEXT,pi_operation_id TEXT,PRIMARY KEY(run_id,event_id),UNIQUE(run_id,turn_seq)) STRICT;INSERT INTO discussion_turns SELECT * FROM discussion_turns_v1;DROP TABLE discussion_turns_v1;COMMIT;PRAGMA foreign_keys=ON;`)}this.db.exec("PRAGMA user_version=2")}
  private tx<T>(fn:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const x=fn();this.db.exec("COMMIT");return x}catch(e){this.db.exec("ROLLBACK");throw e}}
  createOrGet(task:TaskRequest,principal:string,capacity:number,triggerContent?:string):RunView{return this.tx(()=>{
    const old=this.db.prepare("SELECT * FROM tasks WHERE task_id=?").get(task.task_id) as any;
    if(old){if(old.identity_state==="Tombstone")throw new PikoError("Gone",410,"task identity was purged");if(!sameTask(JSON.parse(old.task_json),task))throw new PikoError("TaskConflict",409,"task_id has a different definition");return this.getRun(old.run_id)}
    if(new Date(task.limits.deadline_at).getTime()<=Date.now())throw new PikoError("DeadlineExpired",422,"deadline has elapsed");
    const q=(this.db.prepare("SELECT count(*) n FROM runs WHERE state='Queued'").get() as any).n as number;if(q>=capacity)throw new PikoError("QueueFull",429,"queue is full");
    const run=`run-${randomUUID()}`,accepted=now(),purge=new Date(Math.max(Date.parse(task.limits.deadline_at),Date.now())+7*864e5).toISOString();
    this.db.prepare("INSERT INTO tasks VALUES(?,?,?,?,?,?,?)").run(task.task_id,run,principal,"Active",JSON.stringify(task),accepted,purge);
    this.db.prepare("INSERT INTO runs(run_id,state,generation,cancel_requested,discussion_intake_state,accepted_at,deadline_at,max_model_calls,max_tool_calls) VALUES(?, 'Queued',1,0,?,?,?,?,?)").run(run,task.discussion?"Open":"Disabled",accepted,task.limits.deadline_at,task.limits.max_model_calls,task.limits.max_tool_calls);
    if(task.discussion)this.db.prepare("INSERT INTO discussion_turns VALUES(?,?,1,'Pending',?,NULL,NULL)").run(run,task.discussion.trigger_event_id,triggerContent??"");
    return this.getRun(run)
  })}
  getTask(runId:string):TaskRequest{const r=this.db.prepare("SELECT task_json FROM tasks WHERE run_id=? AND identity_state='Active'").get(runId) as any;if(!r)throw new PikoError("NotFound",404,"run not found");return JSON.parse(r.task_json)}
  findExisting(task:TaskRequest):RunView|null{const old=this.db.prepare("SELECT * FROM tasks WHERE task_id=?").get(task.task_id) as any;if(!old)return null;if(old.identity_state==="Tombstone")throw new PikoError("Gone",410,"task identity was purged");if(!sameTask(JSON.parse(old.task_json),task))throw new PikoError("TaskConflict",409,"task_id has a different definition");return this.getRun(old.run_id)}
  getRun(runId:string):RunView{const r=this.db.prepare("SELECT r.*,t.task_id FROM runs r JOIN tasks t USING(run_id) WHERE r.run_id=?").get(runId) as any;if(!r){const t=this.db.prepare("SELECT identity_state FROM tasks WHERE run_id=?").get(runId) as any;if(t?.identity_state==="Tombstone")throw new PikoError("Gone",410,"run was purged");throw new PikoError("NotFound",404,"run not found")};return {run_id:r.run_id,task_id:r.task_id,state:r.state,accepted_at:r.accepted_at,started_at:r.started_at,finished_at:r.finished_at,result_available:!!this.db.prepare("SELECT 1 FROM results WHERE run_id=?").get(runId),cancel_requested:!!r.cancel_requested,progress:{model_calls:r.model_calls,tool_calls:r.tool_calls,last_activity_at:r.last_activity_at}}}
  nextQueued(owner:string,boot:string):{run_id:string;lease_epoch:number}|null{return this.tx(()=>{const slot=this.db.prepare("SELECT * FROM execution_slot WHERE slot_id=1").get() as any;if(slot.run_id)return null;const r=this.db.prepare("SELECT run_id FROM runs WHERE state='Queued' ORDER BY accepted_at,run_id LIMIT 1").get() as any;if(!r)return null;const epoch=slot.lease_epoch+1;this.db.prepare("UPDATE execution_slot SET run_id=?,owner_id=?,boot_id=?,lease_epoch=?,heartbeat_at=? WHERE slot_id=1").run(r.run_id,owner,boot,epoch,now());this.db.prepare("UPDATE runs SET state='Running',started_at=?,last_activity_at=? WHERE run_id=? AND state='Queued'").run(now(),now(),r.run_id);this.db.prepare("INSERT OR IGNORE INTO run_sessions VALUES(?,?,'main',NULL,NULL,NULL,?)").run(r.run_id,r.run_id,epoch);this.db.prepare("UPDATE run_sessions SET lease_epoch=? WHERE run_id=?").run(epoch,r.run_id);return {run_id:r.run_id,lease_epoch:epoch}})}
  recoverOrphaned(owner:string,boot:string):{run_id:string;lease_epoch:number}|null{return this.tx(()=>{const slot=this.db.prepare("SELECT * FROM execution_slot WHERE slot_id=1").get() as any;if(!slot.run_id)return null;const run=this.db.prepare("SELECT state FROM runs WHERE run_id=?").get(slot.run_id) as any;if(!run||["Completed","Failed","Cancelled"].includes(run.state)){this.db.prepare("UPDATE execution_slot SET run_id=NULL,owner_id=NULL,boot_id=NULL,heartbeat_at=NULL WHERE slot_id=1").run();return null}const epoch=slot.lease_epoch+1;this.db.prepare("UPDATE execution_slot SET owner_id=?,boot_id=?,lease_epoch=?,heartbeat_at=? WHERE slot_id=1").run(owner,boot,epoch,now());this.db.prepare("UPDATE run_sessions SET lease_epoch=? WHERE run_id=?").run(epoch,slot.run_id);return {run_id:slot.run_id,lease_epoch:epoch}})}
  reserveModel(run:string,op:string,step:string,attempt:number):boolean{return this.tx(()=>{const ex=this.db.prepare("SELECT state FROM model_attempts WHERE run_id=? AND operation_id=? AND step_id=? AND attempt=?").get(run,op,step,attempt);if(ex)return true;const r=this.db.prepare("SELECT model_calls,max_model_calls FROM runs WHERE run_id=?").get(run) as any;if(r.model_calls>=r.max_model_calls)return false;this.db.prepare("INSERT INTO model_attempts VALUES(?,?,?,?, 'Started',NULL,1,?)").run(run,op,step,attempt,now());this.db.prepare("UPDATE runs SET model_calls=model_calls+1,last_activity_at=? WHERE run_id=?").run(now(),run);return true})}
  observeUsage(run:string,op:string,step:string,attempt:number,raw:unknown){this.db.prepare("UPDATE model_attempts SET state='UsageObserved',raw_usage_json=?,record_version=record_version+1,updated_at=? WHERE run_id=? AND operation_id=? AND step_id=? AND attempt=?").run(JSON.stringify(raw),now(),run,op,step,attempt)}
  terminalModel(run:string,op:string,step:string,attempt:number){this.db.prepare("UPDATE model_attempts SET state=CASE WHEN raw_usage_json IS NULL THEN 'Terminal' ELSE 'UsageObserved' END,record_version=record_version+1,updated_at=? WHERE run_id=? AND operation_id=? AND step_id=? AND attempt=?").run(now(),run,op,step,attempt)}
  reserveTool(run:string,op:string,id:string,name:string,effect:string,replay:string,contract?:string):"Admitted"|"BudgetExceeded"|"UnsafeRetryBlocked"{return this.tx(()=>{const ex=this.db.prepare("SELECT replay,state FROM tool_calls WHERE run_id=? AND operation_id=? AND tool_call_id=?").get(run,op,id) as any;if(ex){if(ex.replay!=="safe")return "UnsafeRetryBlocked";this.db.prepare("UPDATE tool_calls SET recovery_count=recovery_count+1,updated_at=? WHERE run_id=? AND operation_id=? AND tool_call_id=?").run(now(),run,op,id);return "Admitted"}const r=this.db.prepare("SELECT tool_calls,max_tool_calls FROM runs WHERE run_id=?").get(run) as any;if(r.tool_calls>=r.max_tool_calls)return "BudgetExceeded";this.db.prepare("INSERT INTO tool_calls VALUES(?,?,?,?,?,?,?,'Reserved',0,?)").run(run,op,id,name,effect,replay,contract??null,now());this.db.prepare("UPDATE runs SET tool_calls=tool_calls+1,last_activity_at=? WHERE run_id=?").run(now(),run);return "Admitted"})}
  terminalTool(run:string,op:string,id:string,unknown=false){this.db.prepare("UPDATE tool_calls SET state=?,updated_at=? WHERE run_id=? AND operation_id=? AND tool_call_id=?").run(unknown?"Unknown":"Terminal",now(),run,op,id)}
  markTurn(run:string,event:string,status:"QueuedInPi"|"Consumed"|"Abandoned",entry?:string,op?:string){this.db.prepare("UPDATE discussion_turns SET status=?,pi_entry_id=coalesce(?,pi_entry_id),pi_operation_id=coalesce(?,pi_operation_id) WHERE run_id=? AND event_id=?").run(status,entry??null,op??null,run,event)}
  pendingTurns(run:string){return this.db.prepare("SELECT * FROM discussion_turns WHERE run_id=? AND status IN('Pending','QueuedInPi') ORDER BY turn_seq").all(run) as any[]}
  ingestTurn(run:string,event:string,content:string):boolean{return this.tx(()=>{const r=this.db.prepare("SELECT discussion_intake_state FROM runs WHERE run_id=?").get(run) as any;if(!r||r.discussion_intake_state!=="Open")return false;const seq=(this.db.prepare("SELECT coalesce(max(turn_seq),0)+1 n FROM discussion_turns WHERE run_id=?").get(run) as any).n;const x=this.db.prepare("INSERT OR IGNORE INTO discussion_turns VALUES(?,?,?,'Pending',?,NULL,NULL)").run(run,event,seq,content);return x.changes===1})}
  openDiscussionRuns(room:string){return this.db.prepare("SELECT r.run_id,t.task_json FROM runs r JOIN tasks t USING(run_id) WHERE r.discussion_intake_state='Open' AND t.identity_state='Active'").all().filter((x:any)=>JSON.parse(x.task_json).discussion?.room_id===room).map((x:any)=>x.run_id) as string[]}
  /** Record that Piko lost access to a discussion room; flags every non-terminal Run bound to it. */
  markDiscussionAccessLost(room:string):string[]{return this.tx(()=>{const rows=this.db.prepare("SELECT r.run_id,t.task_json FROM runs r JOIN tasks t USING(run_id) WHERE t.identity_state='Active' AND r.state NOT IN('Completed','Failed','Cancelled')").all() as any[];const affected=rows.filter(x=>{try{return JSON.parse(x.task_json).discussion?.room_id===room}catch{return false}}).map(x=>x.run_id as string);const at=now();for(const run of affected)this.db.prepare("INSERT OR IGNORE INTO discussion_access_loss VALUES(?,?,?)").run(run,room,at);return affected})}
  discussionAccessLost(run:string):boolean{return !!this.db.prepare("SELECT 1 FROM discussion_access_loss WHERE run_id=?").get(run)}
  recordMatrixEvent(room:string,event:string,sender:string,txn?:string):boolean{const x=this.db.prepare("INSERT OR IGNORE INTO matrix_events VALUES(?,?,?,?,?)").run(room,event,sender,txn??null,now());return x.changes===1}
  hasMatrixEvent(room:string,event:string):boolean{return !!this.db.prepare("SELECT 1 FROM matrix_events WHERE room_id=? AND event_id=?").get(room,event)}
  ingestMatrixEvent(room:string,event:string,sender:string,txn:string|undefined,turns:{run:string;visible:string}[]):boolean{return this.tx(()=>{const inserted=this.db.prepare("INSERT OR IGNORE INTO matrix_events VALUES(?,?,?,?,?)").run(room,event,sender,txn??null,now());if(!inserted.changes)return false;for(const turn of turns){const r=this.db.prepare("SELECT discussion_intake_state FROM runs WHERE run_id=?").get(turn.run) as any;if(r?.discussion_intake_state!=="Open")continue;const seq=(this.db.prepare("SELECT coalesce(max(turn_seq),0)+1 n FROM discussion_turns WHERE run_id=?").get(turn.run) as any).n;this.db.prepare("INSERT INTO discussion_turns VALUES(?,?,?,'Pending',?,NULL,NULL)").run(turn.run,event,seq,turn.visible)}return true})}
  ingestMatrixBatch(events:{room:string;event:string;sender:string;txn?:string;turns:{run:string;visible:string}[]}[],cursor:string){return this.tx(()=>{for(const item of events){const inserted=this.db.prepare("INSERT OR IGNORE INTO matrix_events VALUES(?,?,?,?,?)").run(item.room,item.event,item.sender,item.txn??null,now());if(!inserted.changes)continue;for(const turn of item.turns){const r=this.db.prepare("SELECT discussion_intake_state FROM runs WHERE run_id=?").get(turn.run) as any;if(r?.discussion_intake_state!=="Open")continue;const seq=(this.db.prepare("SELECT coalesce(max(turn_seq),0)+1 n FROM discussion_turns WHERE run_id=?").get(turn.run) as any).n;this.db.prepare("INSERT INTO discussion_turns VALUES(?,?,?,'Pending',?,NULL,NULL)").run(turn.run,item.event,seq,turn.visible)}}this.db.prepare("UPDATE matrix_state SET sync_cursor=? WHERE singleton=1").run(cursor);return events.length})}
  matrixCursor(){return (this.db.prepare("SELECT sync_cursor FROM matrix_state WHERE singleton=1").get() as any).sync_cursor as string|null}
  setMatrixCursor(cursor:string){this.db.prepare("UPDATE matrix_state SET sync_cursor=? WHERE singleton=1").run(cursor)}
  prepareMatrixSend(txn:string,run:string,turn:number,payloadSha:string):{state:string;event_id?:string}{return this.tx(()=>{const old=this.db.prepare("SELECT * FROM matrix_sends WHERE txn_id=?").get(txn) as any;if(old){if(old.payload_sha256!==payloadSha)throw new PikoError("TaskConflict",409,"Matrix transaction payload changed");return old}this.db.prepare("INSERT INTO matrix_sends VALUES(?,?,?,?,NULL,'Pending')").run(txn,run,turn,payloadSha);return {state:"Pending"}})}
  finishMatrixSend(txn:string,event:string){this.db.prepare("UPDATE matrix_sends SET state='Sent',event_id=? WHERE txn_id=?").run(event,txn)}
  unknownMatrixSend(txn:string){this.db.prepare("UPDATE matrix_sends SET state='Unknown' WHERE txn_id=? AND state!='Sent'").run(txn)}
  tryCloseIntake(run:string,epoch:number):boolean{return this.tx(()=>{const pending=(this.db.prepare("SELECT count(*) n FROM discussion_turns WHERE run_id=? AND status IN('Pending','QueuedInPi')").get(run) as any).n;if(pending)return false;const r=this.db.prepare("SELECT discussion_intake_state FROM runs WHERE run_id=? AND EXISTS(SELECT 1 FROM run_sessions WHERE run_id=? AND lease_epoch=?)").get(run,run,epoch) as any;if(!r)return false;if(r.discussion_intake_state==="Closing")return true;if(r.discussion_intake_state!=="Open")return false;return this.db.prepare("UPDATE runs SET discussion_intake_state='Closing' WHERE run_id=? AND discussion_intake_state='Open'").run(run).changes===1})}
  cancel(run:string):{outcome:string;requested_at:string}{return this.tx(()=>{const r=this.getRun(run),at=now();if(["Completed","Failed","Cancelled"].includes(r.state))return {outcome:"AlreadyTerminal",requested_at:at};if(r.state==="Queued"){const result:AgentResult={run_id:run,task_id:r.task_id,generation:1,state:"Cancelled",partial:false,summary:"Cancelled before execution started.",outputs:[],known_actions:[],usage:emptyUsage(),failure:{code:"CancelledByRequest",cause_class:"Cancellation",message:"Cancelled before start."},published_at:at};this.insertResult(result);this.db.prepare("UPDATE discussion_turns SET status='Abandoned' WHERE run_id=? AND status IN('Pending','QueuedInPi')").run(run);this.db.prepare("UPDATE runs SET state='Cancelled',cancel_requested=1,discussion_intake_state=CASE WHEN discussion_intake_state='Disabled' THEN 'Disabled' ELSE 'Closed' END,finished_at=? WHERE run_id=?").run(at,run);return {outcome:"CancelledBeforeStart",requested_at:at}}this.db.prepare("UPDATE runs SET state='Cancelling',cancel_requested=1,discussion_intake_state=CASE WHEN discussion_intake_state='Open' THEN 'Closing' ELSE discussion_intake_state END WHERE run_id=?").run(run);return {outcome:"StopRequested",requested_at:at}})}
  heartbeat(run:string,epoch:number):boolean{const x=this.db.prepare("UPDATE execution_slot SET heartbeat_at=? WHERE slot_id=1 AND run_id=? AND lease_epoch=?").run(now(),run,epoch);return x.changes===1}
  cancelRequested(run:string):boolean{return !!(this.db.prepare("SELECT cancel_requested FROM runs WHERE run_id=?").get(run) as any)?.cancel_requested}
  generation(run:string):number{return (this.db.prepare("SELECT generation FROM runs WHERE run_id=?").get(run) as any).generation}
  usage(run:string){return this.db.prepare("SELECT raw_usage_json FROM model_attempts WHERE run_id=? AND raw_usage_json IS NOT NULL").all(run).map((r:any)=>{const value=JSON.parse(r.raw_usage_json);if(value.cost&&typeof value.input==="number"&&typeof value.cacheRead==="number"&&typeof value.cacheWrite==="number"&&typeof value.output==="number"&&value.totalTokens===value.input+value.output+value.cacheRead+value.cacheWrite)return {...value,input:value.input+value.cacheRead+value.cacheWrite};return value})}
  knownActions(run:string){const actions:any[]=[];for(const x of this.db.prepare("SELECT operation_id,step_id,attempt,state FROM model_attempts WHERE run_id=? ORDER BY operation_id,step_id,attempt").all(run) as any[])actions.push({kind:"ModelCall",status:x.state==="Unknown"?"Unknown":x.state==="Reserved"||x.state==="Started"?"Unknown":"Completed",description:`${x.operation_id}/${x.step_id} attempt ${x.attempt}`});for(const x of this.db.prepare("SELECT operation_id,tool_call_id,tool_name,state FROM tool_calls WHERE run_id=? ORDER BY operation_id,tool_call_id").all(run) as any[])actions.push({kind:"ToolCall",status:x.state==="Unknown"||x.state==="Reserved"||x.state==="Started"?"Unknown":"Completed",description:`${x.tool_name} ${x.operation_id}/${x.tool_call_id}`});for(const x of this.db.prepare("SELECT txn_id,state FROM matrix_sends WHERE run_id=? ORDER BY txn_id").all(run) as any[])actions.push({kind:"MatrixSend",status:x.state==="Sent"?"Completed":"Unknown",description:x.txn_id});return actions}
  private insertResult(result:AgentResult){validateUsage(result.usage);const json=JSON.stringify(result);const sha=createHash("sha256").update(json).digest("hex");this.db.prepare("INSERT INTO results VALUES(?,?,?,?,?)").run(result.run_id,result.generation,json,sha,result.published_at)}
  finish(result:AgentResult,epoch:number){this.tx(()=>{const slot=this.db.prepare("SELECT run_id,lease_epoch FROM execution_slot WHERE slot_id=1").get() as any;if(slot.run_id!==result.run_id||slot.lease_epoch!==epoch)throw new PikoError("LeaseLost",409,"execution lease was lost");const run=this.db.prepare("SELECT discussion_intake_state FROM runs WHERE run_id=?").get(result.run_id) as any;const pending=(this.db.prepare("SELECT count(*) n FROM discussion_turns WHERE run_id=? AND status IN('Pending','QueuedInPi')").get(result.run_id) as any).n as number;if(result.state==="Completed"&&run.discussion_intake_state!=="Disabled"&&(run.discussion_intake_state!=="Closing"||pending!==0))throw new PikoError("DiscussionNotClosed",409,"discussion result cannot complete before intake closes");if(result.state!=="Completed")this.db.prepare("UPDATE discussion_turns SET status='Abandoned' WHERE run_id=? AND status IN('Pending','QueuedInPi')").run(result.run_id);this.insertResult(result);this.db.prepare("UPDATE runs SET state=?,finished_at=?,discussion_intake_state=CASE WHEN discussion_intake_state='Disabled' THEN 'Disabled' ELSE 'Closed' END WHERE run_id=?").run(result.state,result.published_at,result.run_id);this.db.prepare("UPDATE execution_slot SET run_id=NULL,owner_id=NULL,boot_id=NULL,heartbeat_at=NULL WHERE slot_id=1 AND run_id=? AND lease_epoch=?").run(result.run_id,epoch)})}
  result(run:string):AgentResult{const r=this.db.prepare("SELECT result_json FROM results WHERE run_id=?").get(run) as any;if(r)return JSON.parse(r.result_json);const state=this.getRun(run).state;if(!["Completed","Failed","Cancelled"].includes(state))throw new PikoError("RunNotTerminal",409,"run is not terminal");throw new PikoError("ResultUnavailable",500,"terminal result missing")}
  purgeExpired(at=now()){return this.tx(()=>{const rows=this.db.prepare("SELECT task_id,run_id FROM tasks WHERE identity_state='Active' AND purge_after<? AND EXISTS(SELECT 1 FROM runs WHERE runs.run_id=tasks.run_id AND state IN('Completed','Failed','Cancelled'))").all(at) as any[];for(const x of rows){for(const table of ["matrix_sends","discussion_turns","discussion_access_loss","tool_calls","model_attempts","results","run_sessions"] )this.db.prepare(`DELETE FROM ${table} WHERE run_id=?`).run(x.run_id);this.db.prepare("DELETE FROM runs WHERE run_id=?").run(x.run_id);this.db.prepare("UPDATE tasks SET identity_state='Tombstone',task_json=NULL WHERE task_id=?").run(x.task_id)}return rows.length})}
}
