import {afterEach,describe,expect,it,vi} from "vitest";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join,relative} from "node:path";
import {MatrixRuntime} from "../../src/matrix.js";
import {TaskStore} from "../../src/store.js";
import type {RuntimeConfig,TaskRequest} from "../../src/types.js";

const stores:TaskStore[]=[];const roots:string[]=[];afterEach(async()=>{for(const store of stores.splice(0))store.close();for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});vi.unstubAllGlobals()});
const config={instance_id:"piko-test",workspace:{staging_root:"/tmp/piko-matrix-test"},matrix:{enabled:true,user_id:"@piko:test",max_media_bytes:16,allowed_mime_types:["text/plain"]}} as RuntimeConfig;
const task:TaskRequest={task_id:"t",instruction:"x",workspace_ref:"repo",permissions:{read_paths:[],write_paths:[],tool_profile_ref:"workspace-standard"},limits:{deadline_at:new Date(Date.now()+60000).toISOString(),max_model_calls:1,max_tool_calls:1},output_paths:[],discussion:{room_id:"!room:test",trigger_event_id:"$event"}};

class FakeMatrix extends MatrixRuntime{
  calls:{room:string;txn:string;body:string;reply?:string}[]=[];fail=true;
  override async send(room:string,txn:string,body:string,reply?:string){this.calls.push({room,txn,body,...(reply?{reply}:{})});if(this.fail){this.fail=false;throw new Error("uncertain send")}return {event_id:"$reply"} as any}
}

describe("Matrix stable sends",()=>{
  it("reuses one transaction id after an uncertain send and suppresses a sent retry",async()=>{const store=new TaskStore(":memory:",1000);stores.push(store);const run=store.createOrGet(task,"slinky",10,"trigger");const matrix=new FakeMatrix(config,store);await expect(matrix.sendDiscussionReply(run.run_id,"!room:test","$event",1,"answer")).rejects.toThrow(/uncertain/);await expect(matrix.sendDiscussionReply(run.run_id,"!room:test","$event",1,"answer")).resolves.toBe("$reply");await expect(matrix.sendDiscussionReply(run.run_id,"!room:test","$event",1,"answer")).resolves.toBe("$reply");expect(matrix.calls).toHaveLength(2);expect(matrix.calls[0]).toEqual(matrix.calls[1]);expect(matrix.calls[0]?.reply).toBe("$event")});
  it("routes one event only to open Runs in its room, records self echoes, and deduplicates retries",async()=>{const store=new TaskStore(":memory:",1000);stores.push(store);const same=store.createOrGet(task,"slinky",10,"trigger");store.markTurn(same.run_id,"$event","Consumed");store.createOrGet({...task,task_id:"other",discussion:{room_id:"!other:test",trigger_event_id:"$other"}},"slinky",10,"other");const matrix=new MatrixRuntime(config,store) as any;matrix.client={getJoinedRooms:async()=>({joined_rooms:["!room:test"]})};const event=(id:string,sender="@user:test")=>({getType:()=>"m.room.message",getRoomId:()=>"!room:test",getId:()=>id,getSender:()=>sender,getUnsigned:()=>({}),getContent:()=>({msgtype:"m.text",body:"hello"})});await matrix.processBatch([event("$one"),event("$self","@piko:test")],"cursor-1");await matrix.processBatch([event("$one")],"cursor-2");expect(store.pendingTurns(same.run_id).map((x:any)=>x.event_id)).toEqual(["$one"]);expect(store.hasMatrixEvent("!room:test","$self")).toBe(true);expect(store.matrixCursor()).toBe("cursor-2")});
  it("fails a batch without advancing the cursor when room membership was revoked",async()=>{const store=new TaskStore(":memory:",1000);stores.push(store);const run=store.createOrGet(task,"slinky",10,"trigger");const matrix=new MatrixRuntime(config,store) as any;matrix.client={getJoinedRooms:async()=>({joined_rooms:[]})};const event={getType:()=>"m.room.message",getRoomId:()=>"!room:test",getId:()=>"$lost",getSender:()=>"@user:test",getUnsigned:()=>({}),getContent:()=>({msgtype:"m.text",body:"hello"})};await expect(matrix.processBatch([event],"cursor-lost")).rejects.toThrow(/no longer joined/);expect(store.matrixCursor()).toBeNull();expect(store.hasMatrixEvent("!room:test","$lost")).toBe(false);expect(store.discussionAccessLost(run.run_id)).toBe(true)});
  it("rejects invalid media URL, size, and MIME before downloading",async()=>{const store=new TaskStore(":memory:",1000);stores.push(store);const matrix=new MatrixRuntime(config,store) as any;matrix.client={mxcUrlToHttp:()=>"https://matrix.test/file"};const base={body:"x.txt",info:{size:4,mimetype:"text/plain"}};await expect(matrix.downloadMedia("run","$e",{...base,url:"https://bad"})).rejects.toThrow(/media URL/);await expect(matrix.downloadMedia("run","$e",{...base,url:"mxc://test/x",info:{...base.info,size:99}})).rejects.toThrow(/size/);await expect(matrix.downloadMedia("run","$e",{...base,url:"mxc://test/x",info:{...base.info,mimetype:"application/x-bad"}})).rejects.toThrow(/MIME/)});
  it("rejects response MIME and byte-count mismatches",async()=>{const store=new TaskStore(":memory:",1000);stores.push(store);const matrix=new MatrixRuntime(config,store) as any;matrix.client={mxcUrlToHttp:()=>"https://matrix.test/file"};const content={body:"x.txt",url:"mxc://test/x",info:{size:4,mimetype:"text/plain"}};vi.stubGlobal("fetch",vi.fn(async()=>new Response("data",{headers:{"content-type":"application/json"}})));await expect(matrix.downloadMedia("run","$e",content)).rejects.toThrow(/MIME mismatch/);vi.stubGlobal("fetch",vi.fn(async()=>new Response("too-long",{headers:{"content-type":"text/plain"}})));await expect(matrix.downloadMedia("run","$e",content)).rejects.toThrow(/size|exceeds/)});
  it("writes a valid attachment inside the Run staging directory with a sanitized basename",async()=>{const root=await mkdtemp(join(tmpdir(),"piko-matrix-"));roots.push(root);const store=new TaskStore(":memory:",1000);stores.push(store);const local={...config,workspace:{staging_root:root}} as RuntimeConfig;const matrix=new MatrixRuntime(local,store) as any;matrix.client={mxcUrlToHttp:()=>"https://matrix.test/file"};vi.stubGlobal("fetch",vi.fn(async()=>new Response("data",{headers:{"content-type":"text/plain"}})));const visible=await matrix.downloadMedia("run-1","$event/../../",{body:"../../secret.txt",url:"mxc://test/x",info:{size:4,mimetype:"text/plain"}});const target=/attachment: (.+) \(text\/plain,/.exec(visible)?.[1];expect(target).toBeTruthy();expect(relative(root,target!).startsWith("..")).toBe(false);expect(target).toMatch(/-secret\.txt$/);expect(await readFile(target!,"utf8")).toBe("data")});
});
