import {describe,expect,it} from "vitest";
import {convertResponsesMessages,processResponsesStream} from "../../upstream/pi/packages/ai/src/api/openai-responses-shared.ts";
import {fauxProvider} from "../../upstream/pi/packages/ai/src/providers/faux.ts";
import {buildBaseOptions} from "../../upstream/pi/packages/ai/src/api/simple-options.ts";

describe("Responses history replay",()=>{
  it("preserves an opaque reasoning item unchanged in the next complete input",()=>{const faux=fauxProvider({api:"openai-responses",provider:"local"});const model=faux.getModel() as any;const reasoning={type:"reasoning",id:"rs_opaque",encrypted_content:"opaque-ciphertext",summary:[{type:"summary_text",text:"summary"}],content:null,status:"completed"};const messages:any[]=[{role:"user",content:"work",timestamp:1},{role:"assistant",content:[{type:"thinking",thinking:"summary",thinkingSignature:JSON.stringify(reasoning)},{type:"toolCall",id:"call_1|fc_1",name:"read",arguments:{path:"x"}}],api:model.api,provider:model.provider,model:model.id,usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:"toolUse",timestamp:2},{role:"toolResult",toolCallId:"call_1|fc_1",toolName:"read",content:[{type:"text",text:"ok"}],isError:false,timestamp:3}];const input=convertResponsesMessages(model,{systemPrompt:"s",messages,tools:[]},new Set(["local"]));expect(input.find((x:any)=>x.type==="reasoning")).toEqual(reasoning);expect(input.some((x:any)=>x.type==="function_call_output")).toBe(true)});
  it("observes terminal provider usage before Pi subtracts cached input",async()=>{const faux=fauxProvider({api:"openai-responses",provider:"local"}),model=faux.getModel() as any;const raw={input_tokens:5676,output_tokens:35,total_tokens:5711,input_tokens_details:{cached_tokens:4096},output_tokens_details:{reasoning_tokens:7}};const events=async function*(){yield {type:"response.completed",response:{id:"r",status:"completed",output:[],usage:raw}} as any};const output:any={role:"assistant",content:[],api:model.api,provider:model.provider,model:model.id,usage:{input:0,output:0,cacheRead:0,cacheWrite:0,totalTokens:0,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:"pending",timestamp:1};let observed:any;await processResponsesStream(events(),output,{push:()=>{}} as any,model,{onRawUsage:value=>{observed=value}});expect(observed).toBe(raw);expect(output.usage).toMatchObject({input:1580,cacheRead:4096,output:35,totalTokens:5711})});
  it("forwards the raw usage observer through streamSimple base options",()=>{const faux=fauxProvider({api:"openai-responses",provider:"local"}),model=faux.getModel() as any;const observer=()=>{};expect(buildBaseOptions(model,{systemPrompt:"",messages:[]},{onRawUsage:observer} as any).onRawUsage).toBe(observer)});
});
